### ISSUE TITLE
[DImgConv] Directories in output path are not created in recursive mode

### ISSUE THREAD

**Issue by biwa** [MTrop/DoomTools#100]
When having a nested directory structure in the source directory and using the `--recursive` switch, the nested directory structure is not created in the output path.

Let's take a directory structure like this:

```
.\source\mymonster\mymoa0.png
.\destination\
```

and run DImgConv like this:

```
dimgconv source --output destination --recursive --palette doom2.wad
```

it will produce this error:

```
ERROR: I/O error on WAD write: destination\mymonster\mymoa0.lmp (The system cannot find the specified path)
```

if the `.\destination\mymonster\` directory is created manually the command works as expected (and if used with DoomMake the files from the nested destination directory are put in the resulting WAD correctly).

**Comment by MTrop** [comment]
Fixed in commit d047e0887c96fc143bfe516378cfa4fa38ff1fb4
