### ISSUE TITLE
[DMXConv] Does not work on directories/no recursive option

### ISSUE THREAD

**Issue by biwa** [MTrop/DoomTools#101]
If you pass an directory as the `files` argument you get an error. For example if I have an directory called `source` and use the following command:

```
dmxconv source
```
I get this error:

```
ERROR: Could not read source.
Calling FFmpeg...
UNSUPPORTED: Java via FFmpeg: Stream of unsupported format
ERROR: Could not find decoder for source. Skipping...
0 of 1 file(s) converted.
```

Using the command with wildcards works:

```
dmxconv source\*.*
```

This is rather unexpected. Also if there are subdirectories in the source directory you get the above error again.

Also there's no way to use the command resurively, unlike for example DImgConv. This means that in DoomMake you can't structure your sounds in subdirectories, where you for example have one directory per monster.

**Comment by MTrop** [comment]
Added in commit a50246023d5ac9f312c4e7b7ed198137005f0608. 

Hope this doesn't break anything!
