### ISSUE TITLE
[DoomMake Studio] Build output is not shown on auto-build

### ISSUE THREAD

**Issue by biwa** [MTrop/DoomTools#102]
Without auto-build the output of DoomMake is shown in the output tab after pressing the "Build!" button, but if auto-build is enabled that doesn't happen. Not even on errors.

**Comment by MTrop** [comment]
This is going to be a little complicated due to how the agent currently does logging, but not insurmountable. It currently logs to the main DoomTools logger, but instead, we'll have to wire it up to the logging panel via its printstreams.

**Comment by MTrop** [comment]
Added in commit 5c48b50a8e9112730f2b7c62bd8504c9d54287bf
