### ISSUE TITLE
[DECOHack] Output warning/error on zero-mass things?

### ISSUE THREAD

**Issue by biwa** [MTrop/DoomTools#103]
Shootable zero-mass things cause most ports to crash: https://www.doomworld.com/forum/topic/141168-i_signalhandler-8-error/

DECOHack does not complain about zero-mass things, but maybe it'd be a good idea if it did.

**Comment by MTrop** [comment]
Seems easy enough. Tough I wonder if it should be a warning rather than an error.

**Comment by biwa** [comment]
I think a warning would be fine. Maybe there's a reason why someone wants zero-mass things. This also only seems to affect shootable things, so maybe DECOHack could check for that.
It could also set the missing mass to 100, which seems to be the default for most non-interactive things.

**Comment by MTrop** [comment]
Added in commit 459a0253024ab9dba59bbc337a0d343767fe41af
