### ISSUE TITLE
[WTExport-GUI] Texture WADs list is not restored from the *.dtw file

### ISSUE THREAD

**Issue by Zalewa** [MTrop/DoomTools#104]
**Doomtools version 2023-08-02**

### Steps
1. Run **doomtools-gui.exe**.
2. **Tools | Textures | WTEXport**
3. Add a bunch of files to the **Textures WADs** list.
4. **File | Save Workspace** - save the `*.dtw` file.
5. Quit program.
6. Run program again.
7. **File | Open Workspace** - select the previously saved `*.dtw` file.

### Result
Files do not reappear on the **Textures WADs** list.

### Extra info
If you inspect the `*.dtw` file in a text editor, there is a `WTExportApp` section and the `files.X` entries appear in the `state` dict. It looks like the files are saved, but not loaded.

There is a similar file list in the `WTexScanApp` section, and the files are loaded properly there.

**Comment by MTrop** [comment]
Hmmm... the files are loaded, but not set in the panel. Easy fix (along with some other fixes).

**Comment by MTrop** [comment]
Fixed in commit ae0756b330cd4772d36a5d2b70fea39155695b8c.
