### ISSUE TITLE
[DoomTools-GUI] version cannot be copied from the About dialog

### ISSUE THREAD

**Issue by Zalewa** [MTrop/DoomTools#105]
**Doomtools version 2023-08-02**

I wanted to copy the version from the about dialog, but it's not possible to select the text there.

Ideally all text in this dialog should be copyable.

**Comment by MTrop** [comment]
The "About" dialog now has a button to copy all version numbers to the clipboard.

Added in commit b09c4405c6ab1d4f8b345c7cfd5535773681aacd.
