### ISSUE TITLE
[DoomTools-GUI] WadMerge editor loads its text from workspace, not from the file

### ISSUE THREAD

**Issue by Zalewa** [MTrop/DoomTools#108]
There is a desynch problem with WadMerge editor (maybe also with other script editors, but I haven't checked)

### Steps

1. In **doomtools-gui** create a workspace and save it.
2. Open the WadMerge editor.
3. Edit the script file in the editor a bit, e.g. add some comments.
4. Save the script file.
5. Save the workspace.
6. Now edit the script file some more, add some more comments
7. Save **ONLY** the script file. **Don't save the workspace** this time.
8. Close **doomtools-gui**.
9. Open new **doomtools-gui** and load the workspace.

### Current result

- The script file on the disk will have the contents from **point 7**.
- The script file in the reopened editor will have the contents form **point 5**.

I assume this is because the body of the editor is saved as base64 in the **dtw** file and then restored from that base64, not from the actual file on the disk. This is done to preserve in the workspace the unsaved editors, right? I think that's not a bad idea, but it's problematic when the file actually is saved. 

You can open this saved **wadm** script file in a text editor while **doomtools-gui** is closed, edit it a bit, and then open the workspace in **doomtools-gui** and it will load not the file, but the body it remembered in the **dtw** file. 

And this is actually what happened to me, where I edited the **wadm** file in Emacs (because it's a more powerful editor) and after putting everything as I wanted, I returned to the GUI. If I had hit the save button in the GUI at this moment, without realising that I'm no longer editing the same file, it would overwrite all my previous work.

**Comment by MTrop** [comment]
I agree. If the date of the file on disk is later than the date of last save in the editor, it should load from disk, instead on restore from workspace.

This should be an easy fix.

**Comment by MTrop** [comment]
Changed in commit 8c12b2a1003c1a6671ccbf1b6decc41e0ee973e8.
