### ISSUE TITLE
[DMXConv] Wrong padding values

### ISSUE THREAD

**Issue by ceski-1** [MTrop/DoomTools#110]
The padding values shouldn't always be `0x7F`. The 16 bytes of padding before the waveform should match the 17th byte (i.e. the first byte of the waveform), while the 16 bytes of padding after the waveform should match the final byte of the waveform. Additional info [here](https://github.com/fabiangreffrath/woof/pull/1133).

**Comment by MTrop** [comment]
You're right - but this correction needs to be done in DoomStruct, not DoomTools.

Issue created: https://github.com/MTrop/DoomStruct/issues/19

**Comment by MTrop** [comment]
Fixed in commit 9fff675bfd4f4a7d8d0cd941c6c7a1322c1524ff.
