### ISSUE TITLE
[DECOHack] Crash on Source Ports when creating auto things in a specific order

### ISSUE THREAD

**Issue by Pedro-Beirao** [MTrop/DoomTools#111]
Weird bug I found and I can't seem to find a fitting name for the issue

Use this .dh file as an example
(Sprite names changed so you dont need the wad)

```
/*****************************************************************************
 * DECOHack Main Patch
 *****************************************************************************/

#include <dsdhacked>
#include <friendly>

weapon 1 "Pistol"
{
	states
	{
		fire:
			PISG A 3
			PISG B 6 A_FirePistol
			PISG C 2
			Goto Ready
	}
}

weapon 3 "Chaingun"
{
	states
	{
		fire:
			CHGG AB 3 A_FireCGun
			CHGG B 0 A_ReFire
			Goto Ready
	}
}

auto thing instabarrel
{
	EdNum 8000

	Health 20
	Radius 10
	Height 42
	
	SeeSound "barexp"
  	
	states
	{
		Spawn:
            		MISL A 10 A_Look
           		Loop
	    	See:
	    		MISL B 5 A_Explode
		   	MISL C 5
		    	MISL D 5
		    	INVI A 1
		    	Wait
	}
}
```

The deh created with this decohack crashes, atleast on dsda-doom and woof

If I change the order to something like `Pistol -> instabarrel -> Chaingun`, it works fine.
For some reason, `Chaingun` needs to be after `instabarrel`

Is it something Im doing wrong? or a bug with decohack?

Fine:
```
Pistol -> instabarrel -> Chaingun
instabarrel -> Pistol -> Chaingun
instabarrel -> Chaingun
```

Crash:
```
Pistol -> Chaingun -> instabarrel
Chaingun  -> instabarrel -> Pistol
Chaingun  -> instabarrel
```

**Comment by MTrop** [comment]
More likely something is happening with your alteration of the Chaingun involving the use of `A_FireCGun`. `A_FireCGun` is a notoriously bad function pointer that relies on it being called from a specific state to function properly. From the function docs:
```
A_FireCGun()
    Fires the chaingun from the calling player.
    Plays the sound "PISTOL", fires one hitscan attack, and subtracts 1 from the ammo type of this weapon.
    This also sets the calling player's state to S_PLAY_ATK2 (state 155).
    If "refire" is 0, the hitscan is dead center.
    NOTE: The FLASH state displayed for this firing is based on the offset from state S_CHAIN1 (52). If 52, FLASH. If 53, FLASH + 1.
```

So, if `A_FireCGun` is called from a later state (which will happen when you replace the state definitions), it will try to use a later state for its muzzle flash, potentially calling a pointer in another definition that it shouldn't.

You might be better off using a different function pointer like `A_WeaponBulletAttack` instead.

**Comment by Pedro-Beirao** [comment]
Hmm, a MBF 21 codepointer for something like this seem overkill, but I'll take it

Still, I find it weird that it works if I change the order of the state definitions.

Close this issue if you think this isnt an issue. Thanks!

**Comment by MTrop** [comment]
You're welcome.

Closing issue.
