### ISSUE TITLE
MERGETEXTUREDIR doesn't set texture size correctly

### ISSUE THREAD

**Issue by skillsawed** [MTrop/DoomTools#13]
All textures imported to TEXTURE2 when using MERGETEXTUREDIR appear to be importing with a size of 0x0. The created patches appear to show the correct size in PNAMES.

![image](https://user-images.githubusercontent.com/47201020/109406851-ec58a680-7941-11eb-948f-43b5d8761f45.png)

I put together a minimal repo to replicate... Clone and run wadmerge on the below to replicate:
[https://github.com/skillsawed/texture-size](https://github.com/skillsawed/texture-size)

**Comment by MTrop** [comment]
Fixed/Revamped in commit ee46b35f3786d23264c1660338a207610f9e9a89
