### ISSUE TITLE
[DECOHack] Add friendly way to reference sound IDs for parameterized codepointers

### ISSUE THREAD

**Issue by XaserAcheron** [MTrop/DoomTools#15]
For parameterized codepointers that take a sound ID as a param (i.e. all one of them at present, A_PlaySound :P ), it'd be nice to have a way to reference the sound by its mnemonic, rather than a number.

Couple of solutions that come to mind are:
- Add a set of `#define`s for sound IDS to the DECOHack "core library", or
- Allow resolving the ID via the syntax `sound [mnemonic]`, e.g. something like `A_PlaySound(sound pistol, 0)`

I'm not picky on the methodology, really; whatever works. :P

**Comment by MTrop** [comment]
Went with the latter: `sound [mnemonic]`

Added in commit fd63b63a07fb1f1f457108bd91fef9edf99dcf3f
