### ISSUE TITLE
[DecoHack] Melee range flag on enemies can't be set properly

### ISSUE THREAD

**Issue by punchyouinthefaceman** [MTrop/DoomTools#25]
For context (since I'm not a programmer and don't understand this stuff) here's an exchange I had with Kraflab:
ME: Melee range might be bugged. I set it to 68 for a pinky and it wouldn't attack me, even going to 128 it just never tried to byte.
KRAFLAB: Guessing that you're trying to set a fixed point field, doom's way of storing fractional values. In that case 65536 ﻿is equal to one unit. Then 68 would be 4456448. Tools can take care of that conversion for you, if you don't mind waiting for them to be ready - otherwise you can take care of the math by hand too. 

Setting melee range to 4456448 in DecoHack returns this error message:
ERROR: Line 549, Token "}": Melee range value (4456448) not between 0 and 65535, inclusively.
A_WeaponMelee can set attack range by map units directly so I assume this is just an inconsistency.

**Comment by MTrop** [comment]
Either I'm writing the wrong value to the resultant DEH file or I'm accepting the wrong type of number. Whoops!

Do you have a sample snippet of code that I can run in DECOHack to diagnose the issue? 

Thanks for reporting!

**Comment by punchyouinthefaceman** [comment]
#include <mbf21>
thing 13
{
	Speed 15
	meleerange 68
}

//Then find a pinky and try to get him to bite you

**Comment by MTrop** [comment]
Fixed in commit 2725487ccde759dc92c34d74cc7c7787ccc8d1ff
