### ISSUE TITLE
[DECOHack] Splashgroup outputs as projectilegroup

### ISSUE THREAD

**Issue by punchyouinthefaceman** [MTrop/DoomTools#27]
//compile this and look at the output .deh, it sets a Projectile group of value 2 instead of a Splash group
#include <mbf21>
thing 1
{
	splashgroup 2
}

thing 34
{
	splashgroup 2
}

**Comment by MTrop** [comment]
Looks like it's setting the wrong field on the thing. Copy-paste strikes again!

**Comment by MTrop** [comment]
Fixed in commit c9e66cda3d3196f3b4ab3a4c6a9cc50e3d9eb93c
