### ISSUE TITLE
[WadMerge] mergedir lump ordering is random-ish on Ubuntu

### ISSUE THREAD

**Issue by XaserAcheron** [MTrop/DoomTools#5]
Noticed an inconsistency in wadmerge's `mergedir` between Windows and Ubuntu*: on the former, all the files in the folder get arranged in nice alphanumeric order (probably case insensitive, but I haven't checked), whereas on the latter, they end up in some sort of quasi-random order. Guessing whatever Java's doing to list the contents of a directory is not automatically sorting 'em in 'nix systems (or relying on the OS to do it)? Either way, the end result is kinda difficult to work with.

My own 'test' case for this is that mod repo I gave you access to recentlyish -- when building on Ubuntu, a bunch of animated flats in E2M1 (MAP04) get all scrambled up, which looks funny as hell in-game but definitely isn't the intended result. :P

I guess fixing this is somewhat opinionated, since you'd kinda have to just Pick Something(tm) as the sort order, but IMO the behavior ought to be well-defined so the same wadmerge command doesn't produce different results on different systems. That and it'd be rather nice to just presume some sort of alphanumeric order is enforced and name animated flats to suit rather than deal with an explicit list of things somewhere (at least for Boom projects where I don't have to care 'bout shoving textures between vanilla names -- WTexport is probably super-nice but that'd be yet another tool in the chain).

[*I'm sure this is more of a general *nix thing than an Ubuntu thing, just listing the one I'm using.]

**Comment by MTrop** [comment]
Ah, I was wondering when this was gonna rear its (very untested) head. I should probably make a sort function that will ensure a consistent order across all OSes for non-directory files.

For animated flats specifically, though, you may be better off merging them in via another WAD file that will keep their strict ordering (at least for Vanilla projects) if an alphabetized order does not suffice.

**Comment by MTrop** [comment]
Reclassifying as "bug" - I do this in one directory import function, but not the other. D'oh!

**Comment by MTrop** [comment]
Committed a fix: 4590ff7c690d7b6038224ca811709557aae61f66

**Comment by XaserAcheron** [comment]
Thanks for the fix! Everything works great on my end after pulling in the changes. :D
