### ISSUE TITLE
[DECOHack] Negative integer values

### ISSUE THREAD

**Issue by punchyouinthefaceman** [MTrop/DoomTools#53]
Say you want a higher chance of gibbing a monster by doing something like TNT1 A 0 A_JumpIfHealthBelow("xdeath", -1) on the first frame of an enemy's death state. You can set this value by hand in the dehacked patch itself and it will work fine but it won't compile if you set it in decohack (unless I missed some way to do this).

**Comment by MTrop** [comment]
Fixed!
