### ISSUE TITLE
[DECOHack] Fixed number after "meleerange" property errors out - MBF21 spec 

### ISSUE THREAD

**Issue by rakohus** [MTrop/DoomTools#68]
Full disclosure. This could be an invalid bug, but going off of conversation between Xaser and I, I figured it was worth filing.

Xaser says `meleerange` should accept fixed point numbers. DECOHack expects an int.

This isn't a big deal because DECOHack does give an explicit error that helps lead the way, but according to Xaser it may be against spec.

Example:
`ERROR: (input.dh) Line 337, Token "80.0": Expected positive integer after "meleerange".`

**Comment by MTrop** [comment]
It gets converted to Fixed Point upon export, but I can't think of a single time where a user would want to describe melee range of an actor with fractions of a map unit and not whole numbers, and the *practicality* far outweighs the possibility concerning such a feature.

The "**Speed**" property is another one of those weird cases where it is either *fixed-point OR integer in the DeHackEd file,* but that depends on if its associated Thing is a PROJECTILE or not, respectively. The user is forced to integers there as well in DECOHack (and I think also DECORATE), so they don't need to care about the required output format upon build.

It would be "against spec" if DECOHack wrote the incorrect value to the patch, which it doesn't, so it isn't.

Closing and flagging as **WONTFIX**.
