### ISSUE TITLE
[Installer] Make a Windows Installer

### ISSUE THREAD

**Issue by MTrop** [MTrop/DoomTools#71]
There are murmurs that DoomTools is a pain to install (and add to PATH) for those not very technically savvy.

Well, their prayers are answered! A Windows Installer is being made, and it's tracked in this branch: [Installer](https://github.com/MTrop/DoomTools/tree/Installer)

FULL STEAM AHEAD!

**Comment by biwa** [comment]
This is a great idea. One thing to keep in mind is handling updates. If a user used the installer, but then uses `doomtools --update`, there can be discrepancies between what Windows thinks is installed, and what's really installed.

An interesting feature of InnoSetup is that running an installer for an already installed program will install the new version in the same place. And running the installer with the `/silent` parameter will do that without any user interaction (there's also `/verysilent` which doesn't even show a window). What I did for the new (yet to be published) UDB installer is that the updater downloads and runs the latest installer when updating an installation done using the installer.

**Comment by MTrop** [comment]
That is a good point and suggestion, though I think I can fudge this a little since I can specify what I can additionally uninstall in an `[UninstallDelete]` section, as what actually gets updated/added on update is the JAR in the `/jar` directory, and, in rarer cases, the user will have to run the `doomtools --update-shell` command to re-build any new utilities that may be on the command line. If they don't do that, they can still just re-install.

Doing a complete wipe of the install directory would be a bad idea of course, if users do something like put projects in the install folder (which I don't recommend, but you never know). Maybe something like the following would still be safe:

```
[UninstallDelete]
Type: files; Name: "{app}\jar\*.jar"
```

That way, it will not delete more than it reasonably should outside of what is known. Users can still do a manual cleanup, if need be.

**Comment by MTrop** [comment]
Done with latest release.
