### ISSUE TITLE
[DECOHack] MonsterInfighting Miscellany Entry not Named Clearly

### ISSUE THREAD

**Issue by punchyouinthefaceman** [MTrop/DoomTools#82]
Having a section like:
```
misc
{
	monsterInfighting false
}
```
will output a valid patch but be missing the monster infighting entry (so in this case there would be no misc section in the resulting .deh)

**Comment by MTrop** [comment]
`false` is the default for `monsterInfighting`, hence the lack of changed output. It may be badly named as to what its function is supposed to be. It maybe should have been called `disableMonsterInfighting`, but I'm still not sure what it does.

**Comment by punchyouinthefaceman** [comment]
That was silly of me, it appears to do the opposite of what I thought it did. It makes enemy projectiles hurt monsters regardless of their type (e.g. an Imp can be hurt by an Imp fireball) and allows monsters of the same type to infight. Whacked4 refers to the parameter as "Monsters fight own species" which seems more clear.

**Comment by MTrop** [comment]
Added as `monstersFightOwnSpecies`.

Added in commit e80073cce2a339997c5542f8e32dc402fcfb952c.
