### ISSUE TITLE
Decohack docs mistake with A_ConsumeAmmo

### ISSUE THREAD

**Issue by HALFKOOL** [MTrop/DoomTools#84]
The Decohack usage docs for A_ConsumeAmmo incorrectly assumes there is a state to jump to.
The dehacked patch still compiles correctly, just the usage text is incorrect.
https://github.com/MTrop/DoomTools/blob/375c361e4a9c2bf84e894bbe1133b5da9129e02e/src/main/java/net/mtrop/doom/tools/decohack/data/enums/DEHActionPointerMBF21.java#L232

**Comment by MTrop** [comment]
Fixed in commit a052202e7626d025444b20722fbd2c3e6c00d0e3
