### ISSUE TITLE
DECOHack does not allow negative mass values for things

### ISSUE THREAD

**Issue by HALFKOOL** [MTrop/DoomTools#90]
When using decohack, attempting to give a thing a negative mass value will throw an error:
> Token "-": Expected positive integer after "mass".

[Doomwiki](https://doomwiki.org/wiki/Mass) states:
> When mass is modified using DeHackEd, it may have detrimental effects on gameplay. If an object's mass is negative, then it will be pulled towards the blast or attack.

Here are some barons with -30 mass

https://user-images.githubusercontent.com/84056596/221462559-e495a5e9-6362-4121-9d03-746ac3af4876.mp4

**Comment by MTrop** [comment]
Fixed in commit 086b32a1ce0c259d96ca7b096dadb1e56859a2a8
